[package]
edition = "2021"
name = "redis"
version = "0.1.0"

[dependencies]
async-trait = "0.1"
common = {path = "../../common"}
log = "0.4"
nom = "7.1"
redis_client = {package = "redis", version = "0.23", features = ["tokio-comp"]}
serde = {version = "1.0", features = ["derive"]}
