[package]
edition = "2021"
name = "twamp"
version = "0.1.0"

[dependencies]
bytes = "1.4"
common = {path = "../../common"}
frame = {path = "../frame"}

[dev-dependencies]
iai-callgrind = "0.3.1"

[[bench]]
harness = false
name = "iai_bench"
