# Postgres and PgBouncer
version: "2"
services:
  postgres:
    image: "postgres:15.3-bullseye"
    volumes:
      - "../../target/release:/opt/ga"
      - "./gufo-agent-pg.yml:/etc/gufo-agent.yml"
      - "./run.sh:/run.sh"
      - "./initdb.d:/docker-entrypoint-initdb.d/"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
  pgbouncer:
    image: "bitnami/pgbouncer:1"
    depends_on:
      - postgres
    volumes:
      - "../../target/release:/opt/ga"
      - "./gufo-agent-pgb.yml:/etc/gufo-agent.yml"
      - "./run.sh:/run.sh"
    environment:
      PGBOUNCER_IGNORE_STARTUP_PARAMETERS: extra_float_digits
      POSTGRESQL_HOST: postgres
      POSTGRESQL_USERNAME: postgres
      POSTGRESQL_PASSWORD: secret
      PGBOUNCER_DATABASE: metrics
      POSTGRESQL_DATABASE: metrics
      PGBOUNCER_STATS_USERS: postgres
  query:
    image: "debian:bullseye-slim"
    depends_on:
      - pgbouncer
    volumes:
      - "../../target/release:/opt/ga"
      - "./gufo-agent-query.yml:/etc/gufo-agent.yml"
      - "./run.sh:/run.sh"
    entrypoint: tail -f /dev/null
