[workspace]

members = [
  "agent",
  "common",
  "main",
  "proto/connection",
  "proto/frame",
  "proto/tos",
  "proto/twamp",
  "proto/udp",
  "collectors/block_io",
  "collectors/cpu",
  "collectors/dns",
  "collectors/fs",
  "collectors/http",
  "collectors/memory",
  "collectors/network",
  "collectors/sockets",
  "collectors/twamp_reflector",
  "collectors/twamp_sender",
  "collectors/uptime",
]
