site_name: Gufo Agent
site_description: Gufo Agent Documentation
site_author: Gufo Labs
site_url: "https://docs.gufolabs.com/gufo_agent/"
copyright: "&copy; 2021-23, Gufo Labs"
site_dir: dist/docs/
repo_url: https://github.com/gufolabs/gufo_agent/
repo_name: GitHub
nav:
  - Home: index.md
  - Installation: installation.md
  - Man Pages: man.md
  - Configuration: configuration.md
  - Config Discovery: config_discovery.md
  - Collectors Reference:
      - Overview: collectors/index.md
      - block_io: collectors/block_io.md
      - cpu: collectors/cpu.md
      - dns: collectors/dns.md
      - fs: collectors/fs.md
      - http: collectors/http.md
      - memory: collectors/memory.md
      - network: collectors/network.md
      - sockets: collectors/sockets.md
      - twamp_reflector: collectors/twamp_reflector.md
      - twamp_sender: collectors/twamp_sender.md
      - uptime: collectors/uptime.md
  - Metrics Reference: metrics.md
  - Developers' Guide:
      - Developer's Environment: environment.md
      - Building and Testing: testing.md
      - Creating New Collector: creating_new_collector.md
      - Common Tasks: devcommon.md
      #- Code Quality: codequality.md
      #- Code Base: codebase.md
      - Contributing Guide: CONTRIBUTING.md
      - Code of Conduct: CODE_OF_CONDUCT.md
  - FAQ: faq.md
  - Changelog: CHANGELOG.md
  - License: LICENSE.md
theme:
  name: material
  logo: assets/logo.png
  favicon: assets/logo.png
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
watch:
  - docs/
  - macros.py
plugins:
  - search
  - literate-nav:
      nav_file: SUMMARY.md
  - section-index
  - macros:
      module_name: macros
markdown_extensions:
  - toc:
      permalink: True
  - admonition
  - footnotes
  - pymdownx.highlight:
      anchor_linenums: True
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
