[package]
edition = "2021"
name = "spool"
version = "0.1.0"

[dependencies]
async-trait = "0.1"
common = {path = "../../common"}
log = "0.4"
openmetrics = {path = "../../proto/openmetrics"}
serde = {version = "1.0", features = ["derive"]}
