[package]
edition = "2021"
name = "sockets"
version = "0.1.0"

[dependencies]
async-trait = "0.1"
common = {path = "../../common"}
log = "0.4"
serde = {version = "1.0", features = ["derive"]}
systemstat = "0.2"
