[package]
edition = "2021"
name = "common"
version = "0.1.0"

[dependencies]
async-trait = "0.1"
paste = "1.0"
serde = "1.0"
serde_yaml = "0.9"
thiserror = "1.0"
tokio = {version = "1.29", features = ["time"]}
