name: Publish Releasee
on:
  release:
    types: [published]
jobs:
  build:
    name: Build and upload assets
    runs-on: ubuntu-20.04
    env:
      RUST_ARCH: x86_64-unknown-linux-gnu
    steps:
      - name: Setup Environment
        run: |
          echo "CARGO_HOME=${HOME}/.cargo" >> $GITHUB_ENV
          echo "RUSTUP_HOME=${HOME}/.rustup" >> $GITHUB_ENV
          echo "${HOME}/.cargo/bin" >> $GITHUB_PATH
      # Checkout source code
      - name: Checkout
        uses: actions/checkout@v3
      # Build
      - name: Install Rust
        run: ./tools/build/setup-rust.sh
      - name: Build
        run: ./tools/build/build-all.sh ${{ github.event.release.name }}
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/gufo-agent-*
