name: Publish Releasee
on:
  release:
    types: [published]
jobs:
  build:
    name: Build and upload assets
    runs-on: ubuntu-20.04
    env:
      RUST_ARCH: x86_64-unknown-linux-gnu
    steps:
      - name: Setup Environment
        run: |
          echo "CARGO_HOME=${HOME}/.cargo" >> $GITHUB_ENV
          echo "RUSTUP_HOME=${HOME}/.rustup" >> $GITHUB_ENV
          echo "${HOME}/.cargo/bin" >> $GITHUB_PATH
      # Checkout source code
      - name: Checkout
        uses: actions/checkout@v3
      # Build
      - name: Install Rust
        run: ./tools/build/setup-rust.sh
      - name: Install Cross
        run: cargo install cross --git https://github.com/cross-rs/cross
      - name: Build
        run: ./tools/build/build-all.sh ${{ github.event.release.name }}
      - name: Build deb amd64
        uses: jiro4989/build-deb-action@v2
        with:
          package: gufo-agent
          package_root: dist/deb/amd64
          maintainer: Gufo Labs
          version: ${{ github.event.release.name }}
          arch: amd64
          desc: an universal agent for infrastructure monitoring
      - name: Build deb amd64
        uses: jiro4989/build-deb-action@v2
        with:
          package: gufo-agent
          package_root: dist/deb/amd64
          maintainer: Gufo Labs
          version: ${{ github.event.release.name }}
          arch: amd64
          desc: an universal agent for infrastructure monitoring
      - name: Build deb aarch64
        uses: jiro4989/build-deb-action@v2
        with:
          package: gufo-agent
          package_root: dist/deb/aarch64
          maintainer: Gufo Labs
          version: ${{ github.event.release.name }}
          arch: aarch64
          desc: an universal agent for infrastructure monitoring
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/gufo-agent-*
