name: Run Tests
on:
  push:
    paths:
      - "**.rs"
      - "**.toml"
jobs:
  rust-tests:
    runs-on: ubuntu-20.04
    env:
      RUST_ARCH: x86_64-unknown-linux-gnu
    steps:
      - name: Setup Environment
        run: |
          echo "CARGO_HOME=${HOME}/.cargo" >> $GITHUB_ENV
          echo "RUSTUP_HOME=${HOME}/.rustup" >> $GITHUB_ENV
          echo "${HOME}/.cargo/bin" >> $GITHUB_PATH

      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Install Rust
        run: ./tools/build/setup-rust.sh

      - name: Install Rust Components
        run: |
          rustup component add rustfmt
          rustup component add clippy

      - name: Check Rust Format
        run: cargo fmt --check

      - name: Run Rust Tests
        run: cargo test

      - name: Run Clippy Tests
        run: cargo clippy
